console.log("Titre de la Page : " + document.title)
console.log("Voici l'URL : " + document.URL)
console.log("Nombre Total d'element : " + document.all.length)
console.log(document.body)
console.log("Type du Doc : " + document.doctype)
console.log(" ")
console.log("Type de l'Element : " + document.documentElement)
console.log("Head : " + document.head)
console.log("Nombre d'enfant : " + document.body.children.length + " Enfants")
console.log("Liste de tout les id : " + document.querySelectorAll("[id]"))
console.log(" ")
console.log("Titre Principal : " + document.querySelector("#titre-principal"))
console.log("La Navigation: " + document.querySelector("#navigation"))
console.log("Contenue Principal : " + document.querySelector("#contenu-principal"))
console.log("Pied de Page : " + document.querySelector("#pied-page"))
console.log("Son Nom de Balise : " + document.getElementsByTagName("hr"))
console.log("Nom de Balise : " + document.querySelector("p"))
console.log("Son ID : " + document.getElementById("en-tete"))
console.log(" ")
console.log("Nombre d'Elements avec une classe : " + document.querySelectorAll(".titre").length)
console.log("Liens avec une classe lien-nav : " + document.querySelectorAll(".lien-nav").length)
console.log("Classe Section : " + document.querySelectorAll(".section").length)
console.log("Classe Service : " + document.querySelectorAll(".service").length)
console.log("Nombre d'Elements avec une classe Texte : " + document.querySelectorAll(".texte").length)


